version: '3.8'

networks:
  desafio_backend:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desafio_backend
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    networks:
      - desafio_backend
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_backend
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - desafio_backend

  redis:
    container_name: redis
    image: redis:6.0.16-alpine
    networks:
      - desafio_backend
